# Morning Brief Generator
# Creates a daily morning brief without browser dependency
# Run: powershell -ExecutionPolicy Bypass -File "scripts/morning-brief-generator.ps1"

param(
    [string]$OutputPath = "C:\dev\FsuelsBot\workspace\memory\morning-briefs"
)

$date = Get-Date -Format "yyyy-MM-dd"
$time = Get-Date -Format "HH:mm"

# Ensure output directory exists
if (-not (Test-Path $OutputPath)) {
    New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
}

# Gather data
$tasksJson = Get-Content "C:\dev\FsuelsBot\workspace\memory\tasks.json" -Raw -Encoding UTF8
$tasksJson = $tasksJson -replace '^\xEF\xBB\xBF', ''  # Remove BOM
$tasks = $tasksJson | ConvertFrom-Json

$stateJson = Get-Content "C:\dev\FsuelsBot\workspace\memory\state.json" -Raw -Encoding UTF8
$state = $stateJson | ConvertFrom-Json

# Count tasks by lane
$botCurrent = $tasks.lanes.bot_current.Count
$botQueue = $tasks.lanes.bot_queue.Count
$doneToday = $tasks.lanes.done_today.Count
$human = $tasks.lanes.human.Count

# Get recent errors
$errorCount = 0
if (Test-Path "C:\dev\FsuelsBot\workspace\memory\error-log.jsonl") {
    $errorCount = (Get-Content "C:\dev\FsuelsBot\workspace\memory\error-log.jsonl" | Measure-Object -Line).Lines
}

# Get recent events
$recentEvents = @()
if (Test-Path "C:\dev\FsuelsBot\workspace\memory\events.jsonl") {
    $recentEvents = Get-Content "C:\dev\FsuelsBot\workspace\memory\events.jsonl" -Tail 5
}

# Build brief
$brief = @"
# 🌅 Morning Brief - $date

**Generated:** $time EST
**Status:** $($state.status)

## 📊 Task Board
| Lane | Count |
|------|-------|
| Bot Working | $botCurrent |
| Bot Queue | $botQueue |
| Done Today | $doneToday |
| Human Pending | $human |

## 🎯 Current Focus
$($state.current_task)

## ⏭️ Next Steps
$($state.next_step)

## 🚧 Blockers
$($state.blockers | ForEach-Object { "- **$($_.item)**: $($_.action)" } | Out-String)

## 📈 System Health
- Error log entries: $errorCount
- Last state update: $($state.updated_at)

## 💡 Key Insight
$($state.key_insight)

---
*Auto-generated by morning-brief-generator.ps1*
"@

# Save brief
$briefPath = Join-Path $OutputPath "$date-morning-brief.md"
$brief | Set-Content $briefPath -Encoding UTF8

Write-Host "✅ Morning brief saved: $briefPath" -ForegroundColor Green
Write-Output $briefPath
