// Process 404 URLs from Google Search Console and generate Shopify redirect CSV
const fs = require('fs');

const rawUrls = [
  "https://www.dresslikemommy.com/en-ae/collections/daddy-me-t-shirts/products/daddy-and-me-big-man-little-man-t-shirt?variant=19650381742177",
  "https://www.dresslikemommy.com/collections/sweaters/products/celebrity-parent-child-vest-towel-embroidery",
  "https://www.dresslikemommy.com/en-be/pages/shipping-and-delivery",
  "https://www.dresslikemommy.com/en-au/",
  "https://www.dresslikemommy.com/en-ae/products/family-matching-colorful-sweater-dad-mother-son-daughter",
  "https://www.dresslikemommy.com/en-ae/collections/midi-dresses",
  "https://www.dresslikemommy.com/en-ie/collections/family-matching/products/family-matching-outfits-summer-boho-chic-dress-and-shirt",
  "https://www.dresslikemommy.com/collections/new-arrivals/products/matching-christmas-pajamas-deer-plaid-set",
  "https://www.dresslikemommy.com/en-ae/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/en-at/products/mommy-me-matching-leopard-print-two-piece-swimsuit",
  "https://www.dresslikemommy.com/en-be/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/en-at/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/products/matching-floral-mother-daughter-dresses-outfit",
  "https://www.dresslikemommy.com/en-be/products/mommy-me-matching-leopard-print-two-piece-swimsuit",
  "https://www.dresslikemommy.com/collections/new-arrivals/products/holiday-christmas-bear-family-pajamas",
  "https://www.dresslikemommy.com/en-ch/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/en-se/products/matching-mermaid-scale-print-bikini",
  "https://www.dresslikemommy.com/collections/new-arrivals/products/christmas-family-matching-sleepwear-pajamas-sets",
  "https://www.dresslikemommy.com/en-au/products/modern-cow-print-tankini-swimsuit-set-for-mother-and-daughter-stylish-high-waisted-swimwear-with-ruffle-detail",
  "https://www.dresslikemommy.com/collections/family-matching/products/long-sleeved-pajamas-ice-silk-home-wear",
  "https://www.dresslikemommy.com/en-be/products/matching-mommy-and-me-two-piece-tankini-swimsuit-set",
  "https://www.dresslikemommy.com/en-hk/products/mommy-me-angels-wing-swimsuit",
  "https://www.dresslikemommy.com/en-se/products/family-matching-rainbow-striped-sweater",
  "https://www.dresslikemommy.com/en-ie/products/mother-daughter-matching-deer-print-party-dress",
  "https://www.dresslikemommy.com/collections/new-women-outfits/products/holiday-christmas-bear-family-pajamas",
  "https://www.dresslikemommy.com/en-de/products/matching-mommy-me-sunflower-print-swimsuit",
  "https://www.dresslikemommy.com/collections/maternity-dresses",
  "https://www.dresslikemommy.com/products/lady-cultivate-dress-autumn-parent-child-outfit-wholesale-mother-and-daughter-dress?utm_source=pinterest&utm_campaign=outfy_sm_1491466849_583&utm_medium=socialmedia_post",
  "https://www.dresslikemommy.com/products/one-shoulder-matching-evening-dresses-customize?variant=32490735534177",
  "https://www.dresslikemommy.com/products/one-shoulder-matching-evening-dresses-customize?variant=32490735566945",
  "https://www.dresslikemommy.com/en-hk/products/chiffon-shoulder-less-maternity-dresses-for-photo-shoot-white-front-open",
  "https://www.dresslikemommy.com/en-au/collections/family-matching-swimsuits",
  "https://www.dresslikemommy.com/en-hk/collections/swimsuits",
  "https://www.dresslikemommy.com/en-at/products/family-matching-battery-t-shirts",
  "https://www.dresslikemommy.com/en-fr/products/family-matching-battery-t-shirts",
  "https://www.dresslikemommy.com/en-gr/products/family-matching-battery-t-shirts",
  "https://www.dresslikemommy.com/en-ae/products/family-matching-battery-t-shirts",
  "https://www.dresslikemommy.com/en-at/products/mother-daughter-flag-maxi-dress",
  "https://www.dresslikemommy.com/en-de/products/mother-daughter-flag-maxi-dress",
  "https://www.dresslikemommy.com/en-au/products/family-matching-set-cute-and-stylish-outfits-for-mothers-fathers-and-children",
  "https://www.dresslikemommy.com/en-at/products/matching-outfit-mother-daughter-chiffon-dress",
  "https://www.dresslikemommy.com/en-hk/products/matching-outfit-mother-daughter-chiffon-dress",
  "https://www.dresslikemommy.com/en-ae/products/matching-outfit-mother-daughter-chiffon-dress",
  "https://www.dresslikemommy.com/en-au/products/cute-mother-daughter-matching-swimsuits",
  "https://www.dresslikemommy.com/en-de/products/cute-mother-daughter-matching-swimsuits",
  "https://www.dresslikemommy.com/en-ie/products/cute-mother-daughter-matching-swimsuits",
  "https://www.dresslikemommy.com/en-se/products/mommy-me-matching-floral-v-sling-jumpsuit",
  "https://www.dresslikemommy.com/en-ch/products/elegant-chocolate-brown-monokini-for-mother-daughter-duo-sleek-halter-neckline-with-playful-polka-dot-tie-sides",
  "https://www.dresslikemommy.com/en-fr/products/royal-blue-high-neck-halter-swimsuit-set-with-paisley-print-bottoms-elegant-family-beachwear",
  "https://www.dresslikemommy.com/en-au/products/family-matching-rainbow-striped-sweater",
  "https://www.dresslikemommy.com/en-ch/products/family-matching-rainbow-striped-sweater",
  "https://www.dresslikemommy.com/products/one-shoulder-matching-evening-dresses-customize?variant=32490735665249",
  "https://www.dresslikemommy.com/en-de/products/matching-two-pieces-bikini-ruffle-swimsuit",
  "https://www.dresslikemommy.com/en-hk/products/chic-family-tides-mother-daughter-matching-two-piece-swimsuit-with-skirt-vibrant-versatile-swimwear-collection",
  "https://www.dresslikemommy.com/en-at/products/mommy-me-matching-tribal-print-one-piece-swimsuit",
  "https://www.dresslikemommy.com/comments",
  "https://www.dresslikemommy.com/en-at/products/mommy-me-spring-flowers-dress",
  "https://www.dresslikemommy.com/en-fr/products/casual-family-matching-outfits-mother-and-daughter-tees-father-and-son-t-shirts-mommy-and-baby-clothes-family-clothing",
  "https://www.dresslikemommy.com/en-hk/products/mommy-me-spring-flowers-dress",
  "https://www.dresslikemommy.com/en-hk/collections/popular-mommy-me",
  "https://www.dresslikemommy.com/en-ae/products/casual-family-matching-outfits-mother-and-daughter-tees-father-and-son-t-shirts-mommy-and-baby-clothes-family-clothing",
  "https://www.dresslikemommy.com/en-at/products/mother-daughter-matching-deer-print-party-dress",
  "https://www.dresslikemommy.com/en-be/products/vibrant-halter-neck-one-piece-swimsuit-with-waist-tie-detail-mother-daughter-matching-swimwear-in-exquisite-baroque-print",
  "https://www.dresslikemommy.com/products/matching-mother-and-daughter-pajamas-elephant?utm_campaign=outfy_sm_1502887035_543&utm_medium=socialmedia_post&utm_source=pinterest",
  "https://www.dresslikemommy.com/en-ae/collections/swimsuits/products/mother-daughter-matching-swim-set-abstract-print-two-piece-high-waisted-bikini-with-wrap-skirt",
  "https://www.dresslikemommy.com/en-hk/collections/skirts",
  "https://www.dresslikemommy.com/en-hk/collections/family-matching/products/stylish-and-comfortable-family-matching-outfits",
  "https://www.dresslikemommy.com/en-hk/collections/family-matching/products/tropical-vibes-matching-family-hawaiian-shirt-and-floral-dress",
  "https://www.dresslikemommy.com/en-fr/products/matching-hand-painted-family-four-t-shirt",
  "https://www.dresslikemommy.com/en-hk/collections/family-matching",
  "https://www.dresslikemommy.com/en-hk/pages/shipping-and-delivery",
  "https://www.dresslikemommy.com/en-hk/products/family-matching-smile-t-shirt?variant=12463565111393",
  "https://www.dresslikemommy.com/en-at/account/register",
  "https://www.dresslikemommy.com/en-hk/collections/family-matching-swimsuits",
  "https://www.dresslikemommy.com/en-gr/products/family-matching-smile-t-shirt",
  "https://www.dresslikemommy.com/en-at/products/family-matching-king-queen-prince-princess-t-shirts",
  "https://www.dresslikemommy.com/en-hk/collections/new-arrivals",
  "https://www.dresslikemommy.com/en-au/products/family-matching-smile-t-shirt?variant=12463565111393",
  "https://www.dresslikemommy.com/en-gr/products/royal-blue-high-neck-halter-swimsuit-set-with-paisley-print-bottoms-elegant-family-beachwear",
  "https://www.dresslikemommy.com/en-hk/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/en-fr/products/chiffon-shoulder-less-maternity-dresses-for-photo-shoot-white-front-open",
  "https://www.dresslikemommy.com/en-be/products/royal-blue-high-neck-halter-swimsuit-set-with-paisley-print-bottoms-elegant-family-beachwear",
  "https://www.dresslikemommy.com/en-at/products/elegant-chocolate-brown-monokini-for-mother-daughter-duo-sleek-halter-neckline-with-playful-polka-dot-tie-sides",
  "https://www.dresslikemommy.com/en-hk/collections/family-matching/products/memorable-family-matching-outfits-create-lasting-memories",
  "https://www.dresslikemommy.com/en-ae/products/family-matching-leopard-print-swimwear",
  "https://www.dresslikemommy.com/en-gr/products/maternity-dresses-sweet-heart-chiffon-cloak-maxi-gown",
  "https://www.dresslikemommy.com/en-at/products/casual-family-matching-outfits-mother-and-daughter-tees-father-and-son-t-shirts-mommy-and-baby-clothes-family-clothing",
  "https://www.dresslikemommy.com/en-ie/pages/secure-payments",
  "https://www.dresslikemommy.com/en-ie/collections/pajamas",
  "https://www.dresslikemommy.com/en-at/products/mommy-me-angels-wing-swimsuit",
  "https://www.dresslikemommy.com/en-ie/products/matching-hand-painted-family-four-t-shirt",
  "https://www.dresslikemommy.com/en-at/products/matching-hand-painted-family-four-t-shirt",
  "https://www.dresslikemommy.com/collections/family-matching/products/family-matching-outfits-2016-summer-style-camouflage-t-shirt-fashion-look-mother-daughter-clothes-father-son-boy-girl-clothing?variant=24393642885",
  "https://www.dresslikemommy.com/collections/new-matching-outfits/products/matching-contrast-stitching-long-sleeve-t-shirt",
  "https://www.dresslikemommy.com/products/lace-floral-red-dress-mommy-me?variant=8162011644001",
  "https://www.dresslikemommy.com/en-ae/pages/shipping-and-delivery",
  "https://www.dresslikemommy.com/products/mommy-me-matching-denim-dress?variant=32330768187489",
  "https://www.dresslikemommy.com/en-se/products/dinosaur-family-matching-sweatshirts",
  "https://www.dresslikemommy.com/en-fr/products/parent-child-rainbow-bear-autumn-sweater",
  "https://www.dresslikemommy.com/en-hk/products/casual-family-matching-outfits-mother-and-daughter-tees-father-and-son-t-shirts-mommy-and-baby-clothes-family-clothing",
  "https://www.dresslikemommy.com/collections/matching-outfits/products/mother-daughter-matching-flannel-pajamas",
  "https://www.dresslikemommy.com/en-jp/products/royal-blue-high-neck-halter-swimsuit-set-with-paisley-print-bottoms-elegant-family-beachwear",
  "https://www.dresslikemommy.com/wpm@0.0.256@3c84b172wd96a86fep64966476m4d4d6440/sandbox/products/matching-mommy-me-two-piece-swimsuit?variant=39452574875745",
  "https://www.dresslikemommy.com/collections/matching-outfits/products/matching-sequin-heart-shaped-printed-hoodies",
  "https://www.dresslikemommy.com/en-ae/products/mommy-me-matching-leopard-print-two-piece-swimsuit",
  "https://www.dresslikemommy.com/en-ch/products/matching-hand-painted-family-four-t-shirt",
  "https://www.dresslikemommy.com/en-gr/products/mommy-me-matching-leopard-print-two-piece-swimsuit",
  "https://www.dresslikemommy.com/en-jp/products/matching-hand-painted-family-four-t-shirt",
  "https://www.dresslikemommy.com/collections/matching-outfits/products/mommy-and-me-comfy-cotton-pajamas",
  "https://www.dresslikemommy.com/products/matching-mom-and-daughter-pink-sequins-long-dress",
  "https://www.dresslikemommy.com/en-de/products/matching-mommy-me-tie-dye-jumpsuit-romper",
  "https://www.dresslikemommy.com/en-ch/collections/daddy-me",
  "https://www.dresslikemommy.com/en-se/products/mother-daughter-matching-swim-set-abstract-print-two-piece-high-waisted-bikini-with-wrap-skirt",
  "https://www.dresslikemommy.com/en-fr/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/en-de/products/matching-mermaid-scale-print-bikini",
  "https://www.dresslikemommy.com/en-gr/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/en-de/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/en-ie/products/matching-mommy-me-sunflower-print-swimsuit",
  "https://www.dresslikemommy.com/en-at/collections/midi-dresses",
  "https://www.dresslikemommy.com/en-fr/products/elegant-chocolate-brown-monokini-for-mother-daughter-duo-sleek-halter-neckline-with-playful-polka-dot-tie-sides",
  "https://www.dresslikemommy.com/collections/maxi-dresses/products/matching-maxi-purple-double-rose-patchwork",
  "https://www.dresslikemommy.com/en-se/products/family-matching-summer-island-set",
  "https://www.dresslikemommy.com/en-ie/collections/family-matching-swimsuits",
  "https://www.dresslikemommy.com/en-de/collections/pants",
  "https://www.dresslikemommy.com/en-ch/pages/secure-payments",
  "https://www.dresslikemommy.com/en-au/collections/new-arrivals/products/make-a-splash-with-this-family-matching-floral-outfit",
  "https://www.dresslikemommy.com/products/mommy-and-me-sleepwear-pajamas?variant=29243797700705",
  "https://www.dresslikemommy.com/collections/midi-dresses/products/mother-daughter-vintage-stars-mesh-dress",
  "https://www.dresslikemommy.com/en-se/products/family-matching-tropical-swimsuits",
  "https://www.dresslikemommy.com/wpm@0.0.290@9b91aff1w4418c6afpfb9312f0m353e3d83/web-pixel-shopify-custom-pixel@0533/sandbox/products/family-matching-blue-coconut-swimsuits?variant=19593210298465",
  "https://www.dresslikemommy.com/en-gr/products/mommy-and-me-unicorn-sweater-fall-and-winter",
  "https://www.dresslikemommy.com/en-de/pages/company-information",
  "https://www.dresslikemommy.com/en-jp/products/family-matching-shirt-and-dress-set-yellow-floral-for-a-springtime-look",
  "https://www.dresslikemommy.com/en-se/products/casual-family-matching-outfits-mother-and-daughter-tees-father-and-son-t-shirts-mommy-and-baby-clothes-family-clothing",
  "https://www.dresslikemommy.com/en-ie/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/en-se/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/en-ae/products/family-matching-boss-t-shirts",
  "https://www.dresslikemommy.com/en-fr/products/family-matching-blue-coconut-swimsuits",
  "https://www.dresslikemommy.com/collections/fall-winter/products/mommy-me-matching-floral-v-sling-jumpsuit",
  "https://www.dresslikemommy.com/en-ie/products/casual-family-matching-outfits-mother-and-daughter-tees-father-and-son-t-shirts-mommy-and-baby-clothes-family-clothing",
  "https://www.dresslikemommy.com/en-au/products/casual-family-matching-outfits-mother-and-daughter-tees-father-and-son-t-shirts-mommy-and-baby-clothes-family-clothing",
  "https://www.dresslikemommy.com/wpm@0.0.261@f6c5cfebw0ef9605dpec92f505mf3672ede/sandbox/products/casual-family-matching-outfits-mother-and-daughter-tees-father-and-son-t-shirts-mommy-and-baby-clothes-family-clothing?variant=21662271365",
  "https://www.dresslikemommy.com/collections/new-women-outfits/products/christmas-family-matching-sleepwear-pajamas-sets",
  "https://www.dresslikemommy.com/en-ch/products/chiffon-shoulder-less-maternity-dresses-for-photo-shoot-white-front-open",
  "https://www.dresslikemommy.com/en-gr/products/mommy-daughter-matching-tie-dye-dress",
  "https://www.dresslikemommy.com/wpm@0.0.264@24271aa3w5f39399apdce3a888m968cefc2/sandbox/products/family-matching-bathing-suits-swimwear?variant=39772839247969",
  "https://www.dresslikemommy.com/collections/matching-outfits/products/celebrity-parent-child-vest-towel-embroidery",
  "https://www.dresslikemommy.com/en-hk/collections/jumpers",
  "https://www.dresslikemommy.com/en-jp/collections/midi-dresses",
  "https://www.dresslikemommy.com/en-hk/collections/leggings",
  "https://www.dresslikemommy.com/en-jp/products/matching-mommy-me-sunflower-print-swimsuit",
  "https://www.dresslikemommy.com/en-hk/pages/terms-and-conditions",
  "https://www.dresslikemommy.com/en-hk/collections/sundresses",
  "https://www.dresslikemommy.com/en-hk/collections/mommy-me",
  "https://www.dresslikemommy.com/en-hk/pages/secure-payments",
  "https://www.dresslikemommy.com/en-hk/products/mommy-daughter-matching-tie-dye-dress",
  "https://www.dresslikemommy.com/wpm@0.0.290@9b91aff1w4418c6afpfb9312f0m353e3d83/web-pixel-shopify-custom-pixel@0533/sandbox/products/mommy-me-angels-wing-swimsuit?variant=18471275135073",
  "https://www.dresslikemommy.com/en-ch/collections/swimsuits/products/chic-two-piece-swimsuit-with-skirt-family-matching-swimwear-for-mother-and-daughter-available-in-blue-green-black",
  "https://www.dresslikemommy.com/products/matching-christmas-mother-daughter-dresses",
  "https://www.dresslikemommy.com/en-jp/collections/family-matching-sweaters-jackets",
  "https://www.dresslikemommy.com/en-au/products/matching-outfit-mother-daughter-chiffon-dress",
  "https://www.dresslikemommy.com/en-au/collections/leggings",
  "https://www.dresslikemommy.com/collections/maxi-dresses/products/matching-white-dress-mom-daughter?variant=29816670552161",
  "https://www.dresslikemommy.com/en-jp/products/chic-mother-daughter-one-shoulder-swimsuit-with-playful-ruffles-and-contrasting-stripes-nylon-polyester-blend",
  "https://www.dresslikemommy.com/en-se/collections/daddy-me-shorts",
  "https://www.dresslikemommy.com/en-at/collections/sweaters",
  "https://www.dresslikemommy.com/collections/mini-dresses/products/matching-love-is-all-you-need-t-shirt",
  "https://www.dresslikemommy.com/en-ch/products/mommy-and-me-checkered-sweater-vest-matching-family-outfits",
  "https://www.dresslikemommy.com/en-ie/products/matching-mommy-and-me-hollow-out-bikini",
  "https://www.dresslikemommy.com/en-ae/products/matching-mommy-and-me-hollow-out-bikini",
  "https://www.dresslikemommy.com/en-fr/products/family-matching-boss-t-shirts",
  "https://www.dresslikemommy.com/en-se/products/matching-mommy-and-me-hollow-out-bikini",
  "https://www.dresslikemommy.com/collections/best-sellers/products/mom-daughter-matching-leopard-swimsuit",
  "https://www.dresslikemommy.com/collections/popular-family-matching/products/matching-christmas-pajamas-baby-its-cold-outside",
  "https://www.dresslikemommy.com/en-ae/products/maternity-photography-props-lace-see-through-maternity-dress",
  "https://www.dresslikemommy.com/en-ch/collections/swimsuits/products/chic-family-bonding-mother-daughter-matching-swimsuit-set-with-long-sleeved-cover-up",
  "https://www.dresslikemommy.com/en-at/products/daddy-and-me-like-father-like-son-t-shirt",
  "https://www.dresslikemommy.com/thank_you",
  "https://www.dresslikemommy.com/en-ch/collections/matching-couples-t-shirts",
  "https://www.dresslikemommy.com/en-de/products/mommy-and-me-unicorn-sweater-fall-and-winter",
  "https://www.dresslikemommy.com/products/new-mommy-and-me-matching-turban-headband-set-fashion-boho-floral-topknot-head-wrap-for-mom-and-baby-gifts-2pcs-set-hb010-3",
  "https://www.dresslikemommy.com/en-de/products/daddy-and-me-big-man-little-man-t-shirt",
  "https://www.dresslikemommy.com/en-au/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/en-au/collections/daddy-me/products/father-and-son-matching-swim-trunks-tropical-floral-print-family-swimwear",
  "https://www.dresslikemommy.com/en-at/collections/mommy-me",
  "https://www.dresslikemommy.com/en-gr/products/family-matching-dragon-t-shirts",
  "https://www.dresslikemommy.com/en-au/products/father-and-son-matching-swim-trunks-tropical-paradise-red-and-green-print",
  "https://www.dresslikemommy.com/en-se/products/matching-maxi-double-rose-patchwork",
  "https://www.dresslikemommy.com/collections/best-sellers/products/matching-sleeveless-color-stripes-jumpsuit",
  "https://www.dresslikemommy.com/collections/family-matching-pajamas/products/holiday-christmas-bear-family-pajamas",
  "https://www.dresslikemommy.com/en-fr/products/matching-two-pieces-bikini-ruffle-swimsuit",
  "https://www.dresslikemommy.com/en-fr/products/mommy-and-me-unicorn-sweater-fall-and-winter",
  "https://www.dresslikemommy.com/products/2015-mom-and-daughter-dress-matching-mother-daughter-clothes-dresses-girl-princess-party-dress-women-robe-family-look-clothing?utm_source=pinterest&utm_campaign=outfy_sm_1491843682_612&utm_medium=socialmedia_post",
  "https://www.dresslikemommy.com/en-fr/products/mother-daughter-pastel-mermaid-scales-swimsuit-with-frill-detail",
  "https://www.dresslikemommy.com/en-at/collections/family-matching-pajamas",
  "https://www.dresslikemommy.com/en-de/collections/matching-couples-t-shirts",
  "https://www.dresslikemommy.com/en-at/collections/bottoms",
  "https://www.dresslikemommy.com/en-at/collections/daddy-me",
  "https://www.dresslikemommy.com/en-at/products/matching-two-pieces-bikini-ruffle-swimsuit",
  "https://www.dresslikemommy.com/en-fr/products/mommy-me-spring-flowers-dress",
  "https://www.dresslikemommy.com/en-at/collections/best-sellers",
  "https://www.dresslikemommy.com/en-at/collections/daddy-me-t-shirts",
  "https://www.dresslikemommy.com/en-at/pages/wholesale-drop-shipping",
  "https://www.dresslikemommy.com/en-hk/products/mommy-me-matching-solid-long-dress",
  "https://www.dresslikemommy.com/en-hk/collections/best-sellers",
  "https://www.dresslikemommy.com/products/vintage-matching-flannel-princess-pjs?ref=reachdog",
  "https://www.dresslikemommy.com/collections/best-sellers/products/mommy-me-matching-floral-v-sling-jumpsuit",
  "https://www.dresslikemommy.com/collections/maxi-dresses/products/mother-daughter-short-sleeve-striped-maxi-dress",
  "https://www.dresslikemommy.com/collections/matching-outfits/products/long-sleeved-pajamas-ice-silk-home-wear",
  "https://www.dresslikemommy.com/collections/midi-dresses/products/new-2016-family-matching-clothing-lace-dresses-for-girls-and-mother-family-matching-mother-daughter-clothes-european-girl-dress",
  "https://www.dresslikemommy.com/en-de/products/mommy-me-flamingo-print-striped-swimsuit",
  "https://www.dresslikemommy.com/products/mother-daughter-floral-patchwork-dress",
  "https://www.dresslikemommy.com/a/s/products/matching-striped-ruffled-mid-skirt-dress",
  "https://www.dresslikemommy.com/en-de/products/family-matching-shirt-and-dress-set-yellow-floral-for-a-springtime-look",
  "https://www.dresslikemommy.com/products/mommy-and-me-matching-rainbow-stripe-midi-dresses",
  "https://www.dresslikemommy.com/products/family-matching-christmas-fair-isle-pajamas-red-white-holiday-reindeer-pajama-set-for-kids-and-adults",
  "https://www.dresslikemommy.com/en-ie/collections/mommy-me",
  "https://www.dresslikemommy.com/products/authentic-mother-daughter-dresses-wave-pattern-family-matching-clothes-summer-cotton-t-shirt-family-look-beach-wear-2016?utm_source=pinterest&utm_campaign=outfy_sm_1493136990_322&utm_medium=socialmedia_post",
  "https://www.dresslikemommy.com/collections/family-matching-pajamas/products/matching-christmas-pajamas-deer-plaid-set",
  "https://www.dresslikemommy.com/en-ae/collections/best-sellers",
  "https://www.dresslikemommy.com/en-ch/products/mommy-me-matching-solid-long-dress?variant=39525052219489",
  "https://www.dresslikemommy.com/en-be/products/mommy-me-flamingo-print-striped-swimsuit",
  "https://www.dresslikemommy.com/en-de/products/matching-couple-t-shirt-lo-ve",
  "https://www.dresslikemommy.com/en-de/products/family-matching-yellow-beach-set",
  "https://www.dresslikemommy.com/en-hk/products/matching-mommy-me-sunflower-print-swimsuit",
  "https://www.dresslikemommy.com/en-be/products/matching-hand-painted-family-four-t-shirt",
  "https://www.dresslikemommy.com/en-at/products/father-son-matching-hawaiian-floral-shirts",
  "https://www.dresslikemommy.com/en-fr/products/father-son-matching-hawaiian-floral-shirts",
  "https://www.dresslikemommy.com/en-fr/products/shimmering-silver-grey-party-dress-for-women-and-girls-elegant-a-line-dress-with-cross-back-detail",
  "https://www.dresslikemommy.com/en-ae/collections/family-matching/products/tropical-vibes-matching-family-hawaiian-shirt-and-floral-dress",
  "https://www.dresslikemommy.com/en-jp/products/family-matching-christmas-deer-snowflake-pjs",
  "https://www.dresslikemommy.com/en-au/collections/sweaters",
  "https://www.dresslikemommy.com/en-hk/products/matching-heart-t-shirt-mommy-me",
  "https://www.dresslikemommy.com/en-ae/collections/mommy-me",
  "https://www.dresslikemommy.com/collections/matching-outfits/products/matching-christmas-pajamas-deer-plaid-set",
  "https://www.dresslikemommy.com/en-de/products/matching-heart-t-shirt-mommy-me",
  "https://www.dresslikemommy.com/en-gr/products/family-matching-rule-maker-rule-breaker-t-shirts?variant=32232166162529",
  "https://www.dresslikemommy.com/en-at/products/matching-heart-t-shirt-mommy-me",
  "https://www.dresslikemommy.com/en-ch/collections/family-matching",
  "https://www.dresslikemommy.com/en-se/collections/family-matching-t-shirts",
  "https://www.dresslikemommy.com/en-ie/products/mommy-me-matching-leopard-print-two-piece-swimsuit",
  "https://www.dresslikemommy.com/en-gr/collections/matching-couples-t-shirts",
  "https://www.dresslikemommy.com/products/free-shipping-mother-daughter-dresses-summer-colorful-girls-dress-family-matching-outfits-women-girl-holiday-long-vest-dress?utm_source=pinterest&utm_campaign=outfy_sm_1493664530_924&utm_medium=socialmedia_post",
  "https://www.dresslikemommy.com/products/mommy-me-matching-bohemian-patchwork-dress?variant=7626116988958",
  "https://www.dresslikemommy.com/products/family-matching-stripe-christmas-pajamas?variant=30878263214177",
  "https://www.dresslikemommy.com/en-de/products/family-matching-boss-t-shirts",
  "https://www.dresslikemommy.com/en-ch/collections/leggings",
  "https://www.dresslikemommy.com/en-ch/collections/mommy-me/products/chic-two-piece-swimsuit-with-skirt-family-matching-swimwear-for-mother-and-daughter-available-in-blue-green-black",
  "https://www.dresslikemommy.com/en-ch/products/family-matching-rule-maker-rule-breaker-t-shirts",
  "https://www.dresslikemommy.com/en-au/products/mommy-me-matching-floral-one-piece-swimsuit",
  "https://www.dresslikemommy.com/en-se/products/maternity-photography-props-maxi-dresses-see-through-eyelashes-lace",
  "https://www.dresslikemommy.com/en-ie/products/mommy-and-me-checkered-sweater-vest-matching-family-outfits",
  "https://www.dresslikemommy.com/en-be/products/maternity-photography-props-maxi-dresses-see-through-eyelashes-lace",
  "https://www.dresslikemommy.com/en-gr/products/matching-mommy-and-me-hollow-out-bikini",
  "https://www.dresslikemommy.com/en-ie/products/chiffon-shoulder-less-maternity-dresses-for-photo-shoot-white-front-open",
  "https://www.dresslikemommy.com/en-de/products/chiffon-shoulder-less-maternity-dresses-for-photo-shoot-white-front-open",
  "https://www.dresslikemommy.com/en-au/products/maternity-photography-props-maxi-dresses-see-through-eyelashes-lace",
  "https://www.dresslikemommy.com/en-be/products/mommy-and-me-checkered-sweater-vest-matching-family-outfits",
  "https://www.dresslikemommy.com/collections/family-matching/products/family-matching-long-sleeve-swimwear",
  "https://www.dresslikemommy.com/collections/casual-dresses/products/elegant-sky-blue-mother-daughter-summer-dresses-tiered-ruffle-matching-outfits-for-special-occasions",
  "https://www.dresslikemommy.com/b",
  "https://www.dresslikemommy.com/en-ch/collections/mommy-me/products/elegant-mother-daughter-matching-one-piece-swimsuit-with-patterned-mesh-skirt-family-beachwear-set",
  "https://www.dresslikemommy.com/en-ch/products/family-matching-dragon-t-shirts",
  "https://www.dresslikemommy.com/en-au/products/maternity-photography-props-lace-see-through-maternity-dress",
  "https://www.dresslikemommy.com/en-se/pages/about-us",
  "https://www.dresslikemommy.com/en-se/collections/popular-mommy-me-1/products/parent-child-rainbow-bear-autumn-sweater?variant=40949491925089",
  "https://www.dresslikemommy.com/en-be/products/maternity-photography-props-lace-see-through-maternity-dress",
  "https://www.dresslikemommy.com/en-se/collections/family-matching-sets",
  "https://www.dresslikemommy.com/en-se/pages/secure-payments",
  "https://www.dresslikemommy.com/en-ie/products/mommy-me-cotton-silk-princess-pajamas",
  "https://www.dresslikemommy.com/en-de/collections/family-matching-t-shirts",
  "https://www.dresslikemommy.com/en-se/collections/pants",
  "https://www.dresslikemommy.com/en-jp/products/casual-family-matching-outfits-mother-and-daughter-tees-father-and-son-t-shirts-mommy-and-baby-clothes-family-clothing",
  "https://www.dresslikemommy.com/en-ie/collections/sweaters",
  "https://www.dresslikemommy.com/en-be/products/mother-and-daughter-long-sleeved-dress",
  "https://www.dresslikemommy.com/en-ch/collections/new-matching-outfits",
  "https://www.dresslikemommy.com/en-be/products/family-matching-yellow-beach-set?variant=19793956044897",
  "https://www.dresslikemommy.com/en-au/products/mother-daughter-matching-swim-set-abstract-print-two-piece-high-waisted-bikini-with-wrap-skirt",
  "https://www.dresslikemommy.com/en-hk/products/matching-mamas-boy-t-shirt",
  "https://www.dresslikemommy.com/products/mom-and-baby-matching-knitted-hats-warm-fleece-crochet-beanie-hats-winter-mink-raccoon-fur-kids-children-mommy-headwear-hat-caps-3?variant=21874232069",
  "https://www.dresslikemommy.com/products/mommy-me-splice-summer-maxi-dress",
  "https://www.dresslikemommy.com/en-jp/products/father-and-son-matching-swim-trunks-classic-paisley-pattern-in-blue-and-yellow",
  "https://www.dresslikemommy.com/en-se/pages/terms-and-conditions",
  "https://www.dresslikemommy.com/en-gr/products/mommy-me-angels-wing-swimsuit",
  "https://www.dresslikemommy.com/en-de/products/daddy-and-me-i-have-created-a-monster-t-shirt",
  "https://www.dresslikemommy.com/en-de/products/father-son-matching-hawaiian-floral-shirts",
  "https://www.dresslikemommy.com/en-be/products/father-son-matching-hawaiian-floral-shirts",
  "https://www.dresslikemommy.com/en-ie/products/matching-t-shirt-heart-rate-mommy-me",
  "https://www.dresslikemommy.com/collections/fall-winter/products/mom-daughter-matching-leopard-swimsuit",
  "https://www.dresslikemommy.com/products/family-matching-outfits-mother-daughter-dresses-owl-mom-girl-dress-set-girls-cotton-lien-age-size-2-7-years-old-mom-size-s-m-l",
  "https://www.dresslikemommy.com/wpm@0.0.295@5995fe33we7716795p70e72afbmd3a6af29/web-pixel-shopify-custom-pixel@0538/sandbox/products/cute-mother-daughter-matching-swimsuits?variant=39772475129953",
  "https://www.dresslikemommy.com/en-gr/products/family-matching-giraffe-sweater",
  "https://www.dresslikemommy.com/en-be/products/family-matching-christmas-deer-snowflake-pjs",
  "https://www.dresslikemommy.com/en-at/collections/swimsuits/products/chic-mother-daughter-matching-swimsuit-set-with-floral-cover-up-family-beachwear-collection",
  "https://www.dresslikemommy.com/en-ie/products/family-matching-colorful-sweater-dad-mother-son-daughter",
  "https://www.dresslikemommy.com/products/cotton-christmas-family-matching-pajamas?variant=30878386192481",
  "https://www.dresslikemommy.com/en-de/products/family-matching-summer-island-set",
  "https://www.dresslikemommy.com/products/family-matching-sun-cloud-plant-t-shirt?variant=18620432679009",
  "https://www.dresslikemommy.com/en-au/pages/company-information",
  "https://www.dresslikemommy.com/collections/maternity/products/maternity-ruffles-floral-print-maxi-dress-stretchy",
  "https://www.dresslikemommy.com/products/new-arrival-personalisedmother-and-daughter-we-will-always-be-mother-keychain-key-ring-family-gift-1",
  "https://www.dresslikemommy.com/products/za-new-fashion-brand-winter-scarf-for-women-scarf-luxury-cashmere-shawls-and-scarves-women-wool-plaid-pashmina-wholesale-retail",
  "https://www.dresslikemommy.com/en-de/products/mother-daughter-matching-beach-swimwear",
  "https://www.dresslikemommy.com/products/matching-colorful-geometric-dress",
  "https://www.dresslikemommy.com/en-ch/pages/faqs",
  "https://www.dresslikemommy.com/collections/new-matching-outfits/products/celebrity-parent-child-vest-towel-embroidery",
  "https://www.dresslikemommy.com/en-ch/products/family-matching-outfits-floral-dresses-and-shorts-with-a-touch-of-fun",
  "https://www.dresslikemommy.com/en-fr/products/mother-daughter-matching-deer-print-party-dress",
  "https://www.dresslikemommy.com/en-au/collections/headbands/products/mom-and-me-headband-with-knit-fabric-baby-girl-headband-mommy-and-me-matching-headbands-photo-prop-gift-for-mom-and-baby-1set-7",
  "https://www.dresslikemommy.com/en-au/products/family-matching-boss-t-shirts",
  "https://www.dresslikemommy.com/en-gr/collections/popular-family-matching/products/family-matching-first-time-t-shirts",
  "https://www.dresslikemommy.com/products/matching-maxi-purple-double-rose-patchwork",
  "https://www.dresslikemommy.com/products/matching-mother-daughter-long-sleeve-plaid-lace-patchwork-dress?variant=31302926205025",
  "https://www.dresslikemommy.com/products/new-2016-family-matching-clothing-lace-dresses-for-girls-and-mother-family-matching-mother-daughter-clothes-european-girl-dress?variant=24393305797",
  "https://www.dresslikemommy.com/products/matching-white-dress-mom-daughter",
  "https://www.dresslikemommy.com/en-se/products/family-matching-saurus-t-shirts",
  "https://www.dresslikemommy.com/collections/best-sellers/products/matching-leopard-thick-knit-long-sleeved-shirt",
  "https://www.dresslikemommy.com/paginfo@dresslikemommy.com",
  "https://www.dresslikemommy.com/en-at/products/family-matching-blue-coconut-swimsuits",
  "https://www.dresslikemommy.com/en-ie/products/family-matching-set-cute-and-stylish-outfits-for-mothers-fathers-and-children",
  "https://www.dresslikemommy.com/en-ae/collections/matching-outfits/products/fashion-matching-mother-child-swimsuit?variant=39756867305569",
  "https://www.dresslikemommy.com/en-ee/products/new-baby-and-adult-flower-lace-turban-mom-and-me-match-headband-for-newborn-photo-prop-infant-kid-rhinestone-headwrap-1set-hb027",
  "https://www.dresslikemommy.com/en-ae/products/family-matching-giraffe-sweater",
  "https://www.dresslikemommy.com/en-ch/collections/popular-mommy-me/products/mommy-and-me-sleepwear-pajamas",
  "https://www.dresslikemommy.com/en-be/collections/swimsuits/products/chic-family-tides-mother-daughter-matching-two-piece-swimsuit-with-skirt-vibrant-versatile-swimwear-collection",
  "https://www.dresslikemommy.com/en-be/collections/family-matching/products/family-matching-outfits-floral-dresses-and-shorts-with-a-touch-of-fun",
  "https://www.dresslikemommy.com/en-be/products/casual-family-matching-outfits-mother-and-daughter-tees-father-and-son-t-shirts-mommy-and-baby-clothes-family-clothing",
  "https://www.dresslikemommy.com/en-de/collections/rompers",
  "https://www.dresslikemommy.com/products/word-i-love-you-wife-daughter-mummy-mom-mum-heart-love-family-charm-stainless-steel-pendant-beads-charms-fit-pandora-bracelet-2",
  "https://www.dresslikemommy.com/en-ie/products/mother-daughter-flag-maxi-dress",
  "https://www.dresslikemommy.com/en-be/collections/casual-dresses?constraint=multi-color",
  "https://www.dresslikemommy.com/en-gr/",
  "https://www.dresslikemommy.com/en-at/products/matching-maxi-double-rose-patchwork",
  "https://www.dresslikemommy.com/collections/all/products/matching-maxi-double-rose-patchwork",
  "https://www.dresslikemommy.com/products/2016-new-fashion-mom-and-me-headband-turban-headband-pair-set-top-knotted-headband-set-baby-and-mommy-cotton-headwrap-set-1-set-7",
  "https://www.dresslikemommy.com/en-jp/products/family-matching-fun-beach-set",
  "https://www.dresslikemommy.com/en-ae/products/stylish-and-comfortable-family-matching-outfits?variant=40915961348193",
  "https://www.dresslikemommy.com/en-at/products/mommy-me-flamingo-print-striped-swimsuit",
  "https://www.dresslikemommy.com/en-se/products/mother-daughter-flag-maxi-dress",
  "https://www.dresslikemommy.com/en-au/collections/rompers",
  "https://www.dresslikemommy.com/en-se",
  "https://www.dresslikemommy.com/en-de",
  "https://www.dresslikemommy.com/en-de/products/family-matching-rule-maker-rule-breaker-t-shirts?variant=32232166162529",
  "https://www.dresslikemommy.com/en-fr/collections/casual-dresses?constraint=multi-color",
  "https://www.dresslikemommy.com/en-fr/products/maternity-cotton-mermaid-trumpet-strapless-pregnant-dress",
  "https://www.dresslikemommy.com/en-fr/products/matching-mommy-me-tie-dye-jumpsuit-romper",
  "https://www.dresslikemommy.com/products/matching-mommy-me-pink-dream-dress",
  "https://www.dresslikemommy.com/products/mom-baby-white-lace-matching-swimsuit?variant=29213797777505",
  "https://www.dresslikemommy.com/collections/swimwear",
  "https://www.dresslikemommy.com/products/mommy-me-matching-bohemian-maxi-dress",
  "https://www.dresslikemommy.com/products/maternity-ruffles-floral-print-maxi-dress-stretchy",
  "https://www.dresslikemommy.com/products/2016-family-matching-outfit-mother-and-daughter-clothes-long-sleeve-t-shirt-fashion-print-topsmatching-mother-daughter-clothes?utm_source=pinterest&utm_campaign=outfy_sm_1493142964_301&utm_medium=socialmedia_post",
  "https://www.dresslikemommy.com/en-fr/collections/formal-dresses/products/high-end-princess-gown-dress-customize",
  "https://www.dresslikemommy.com/collections/mommy-me/products/mommy-me-matching-stripe-hem-long-sleeve-top",
  "https://www.dresslikemommy.com/en-ch/collections/family-matching/products/boho-chic-family-matching-outfit-flowy-skirts-and-paisley-shirts",
  "https://www.dresslikemommy.com/en-ch/products/royal-blue-high-neck-halter-swimsuit-set-with-paisley-print-bottoms-elegant-family-beachwear",
  "https://www.dresslikemommy.com/en-at/products/maternity-photography-props-maxi-dresses-see-through-eyelashes-lace",
  "https://www.dresslikemommy.com/en-ch/collections/family-matching/products/memorable-family-matching-outfits-create-lasting-memories",
  "https://www.dresslikemommy.com/collections/casual-dresses/products/mommy-me-lemon-print-matching-dresses",
  "https://www.dresslikemommy.com/en-at/collections/leggings",
  "https://www.dresslikemommy.com/en-ch/pages/return-policy",
  "https://www.dresslikemommy.com/en-hk/products/family-matching-colorful-sweater-dad-mother-son-daughter",
  "https://www.dresslikemommy.com/products/matching-t-shirt-heart-rate-mommy-me",
  "https://www.dresslikemommy.com/en-be/",
  "https://www.dresslikemommy.com/products/mother-daughter-short-sleeve-striped-maxi-dress",
  "https://www.dresslikemommy.com/a/s/products/matching-long-sleeved-shirt",
  "https://www.dresslikemommy.com/en-jp/collections/casual-dresses?constraint=multi-color",
  "https://www.dresslikemommy.com/en-fr/products/matching-mommy-me-sunflower-print-swimsuit",
  "https://www.dresslikemommy.com/en-hk/account/register",
  "https://www.dresslikemommy.com/en-ch/products/family-matching-christmas-deer-snowflake-pjs",
  "https://www.dresslikemommy.com/en-ie",
  "https://www.dresslikemommy.com/products/long-sleeved-pajamas-ice-silk-home-wear?variant=40361387491425",
  "https://www.dresslikemommy.com/products/2016-family-matching-outfits-summer-family-look-mum-and-me-party-bow-clothes-mother-daughter-sloping-shoulder-dress-2-colors",
  "https://www.dresslikemommy.com/products/family-matching-sunny-beach-outfit?variant=18470911246433",
  "https://www.dresslikemommy.com/products/mother-and-daughter-dresses-dresses-for-girls-family-matching-clothing-girls-sleeveless-summer-beach-party-dress",
  "https://www.dresslikemommy.com/products/2016-summer-dress-mother-and-daughter-dresses-family-matching-mother-daughter-clothes-family-clothing-paiting-sleeveless-dress",
  "https://www.dresslikemommy.com/products/matching-mommy-me-tutu-skirts?variant=18607416705121",
  "https://www.dresslikemommy.com/en-ie/",
  "https://www.dresslikemommy.com/products/campure-autumn-matching-mother-daughter-clothes-clouds-style-brand-mother-kids-sweaters-cotton-1-5yrs-baby-boys-girls-clothes",
  "https://www.dresslikemommy.com/en-au/collections/family-matching/products/tropical-vibes-matching-family-hawaiian-shirt-and-floral-dress",
  "https://www.dresslikemommy.com/en-at",
  "https://www.dresslikemommy.com/en-ie/products/family-matching-summer-island-set",
  "https://www.dresslikemommy.com/products/piece-dress-up-dress-up-dress-up-dress-up-dress-up-dress-up-dress-up-dress-up-dress-up",
  "https://www.dresslikemommy.com/en-de/collections/matching-couples-t-shirts/products/couple-matching-t-shirt-funny-beard-butt",
  "https://www.dresslikemommy.com/products/matching-t-shirt-skirt-mom-and-daughter-dress?variant=21576139077",
  "https://www.dresslikemommy.com/products/family-summer-striped-clothing-mom-and-daughter-me-dad-son-mother-matching-clothes-aile-giyim-setleri-outfits-suits-familia",
  "https://www.dresslikemommy.com/collections/swimsuits/products/mother-daughter-vibrant-two-piece-swimsuit-set-with-flowing-skirt-matching-family-swimwear-collection?variant=41498026442849",
  "https://www.dresslikemommy.com/en-se/collections/family-matching-swimsuits",
  "https://www.dresslikemommy.com/products/daddy-and-me-pizza-t-shirt?variant=19650133491809",
  "https://www.dresslikemommy.com/products/mommy-and-me-top-knots-headwrap-set-topknot-headband-mom-and-me-headbands-mom-and-daughter-turban-set-1set-hb536-1?variant=21857967045",
  "https://www.dresslikemommy.com/en-ie/products/matching-mommy-me-unicorn-t-shirt",
  "https://www.dresslikemommy.com/en-ch",
  "https://www.dresslikemommy.com/products/2016-new-mommy-and-me-cotton-turban-head-wrap-set-baby-girl-hair-accessories-printing-knotted-headband-photo-prop-hair-bows-1",
  "https://www.dresslikemommy.com/products/family-matching-summer-colors-swimsuits",
  "https://www.dresslikemommy.com/products/mommy-me-bohemian-floral-retro-printed-dress?variant=8144440426593",
  "https://www.dresslikemommy.com/en-hk/products/father-son-matching-hawaiian-floral-shirts",
  "https://www.dresslikemommy.com/en-au/products/family-matching-dragon-t-shirts",
  "https://www.dresslikemommy.com/en-gr/products/new-striped-matching-mother-daughter-clothes-father-son-outfits-family-look-2016-matching-family-shirts-cotton-family-outfits",
  "https://www.dresslikemommy.com/en-hk/products/daddy-and-me-i-have-created-a-monster-t-shirt",
  "https://www.dresslikemommy.com/products/mommy-me-matching-denim-dress",
  "https://www.dresslikemommy.com/en-be/products/mommy-me-matching-red-dress",
  "https://www.dresslikemommy.com/en-be/collections/daddy-me?page=1",
  "https://www.dresslikemommy.com/collections/midi-dresses/products/matching-leopard-print-lace-dress",
  "https://www.dresslikemommy.com/en-ae/products/chiffon-shoulder-less-maternity-dresses-for-photo-shoot-white-front-open",
  "https://www.dresslikemommy.com/collections/matching-outfits/products/cute-mother-daughter-matching-stripe-dress",
  "https://www.dresslikemommy.com/en-ae/collections/swimsuits/products/mother-daughter-vibrant-two-piece-swimsuit-set-with-flowing-skirt-matching-family-swimwear-collection",
  "https://www.dresslikemommy.com/en-gr/products/matching-big-man-little-man-t-shirts",
  "https://www.dresslikemommy.com/en-ch/collections/family-matching/products/family-matching-outfits-floral-dresses-and-shorts-with-a-touch-of-fun",
  "https://www.dresslikemommy.com/en-fr/products/couple-matching-t-shirt-funny-beard-butt",
  "https://www.dresslikemommy.com/en-ae/collections/new-matching-outfits",
  "https://www.dresslikemommy.com/en-be/products/father-and-son-matching-swim-trunks-tropical-paradise-red-and-green-print",
  "https://www.dresslikemommy.com/products/matching-mother-girl-colorful-chiffon-dress",
  "https://www.dresslikemommy.com/products/one-shoulder-matching-evening-dresses-customize?variant=32490735698017",
  "https://www.dresslikemommy.com/en-gr/products/matching-mommy-me-two-piece-swimsuit",
  "https://www.dresslikemommy.com/en-hk/products/family-matching-dress-and-t-shirt-set-summer-fun-for-the-whole-family",
  "https://www.dresslikemommy.com/collections/daddy-me-t-shirts/products/daddy-me-little-dudes-dad-t-shirts",
  "https://www.dresslikemommy.com/en-jp/products/family-matching-outfits-floral-dresses-and-shorts-with-a-touch-of-fun",
  "https://www.dresslikemommy.com/en-ae/collections/tops",
  "https://www.dresslikemommy.com/en-de/products/family-matching-outfits-floral-dresses-and-shorts-with-a-touch-of-fun",
  "https://www.dresslikemommy.com/en-at/collections/popular-mommy-me/products/matching-heart-t-shirt-mommy-me",
  "https://www.dresslikemommy.com/en-de/collections/family-matching/products/make-a-splash-with-this-family-matching-floral-outfit",
  "https://www.dresslikemommy.com/collections/midi-dresses/products/mother-me-chiffon-floral-long-dress",
  "https://www.dresslikemommy.com/en-ie/products/family-matching-outfits-floral-dresses-and-shorts-with-a-touch-of-fun",
  "https://www.dresslikemommy.com/en-hk/collections/daddy-me",
  "https://www.dresslikemommy.com/en-fr/collections/daddy-me",
  "https://www.dresslikemommy.com/en-au/products/matching-long-sleeved-shirt",
  "https://www.dresslikemommy.com/en-hk",
  "https://www.dresslikemommy.com/en-ee/products/mommy-and-me-sleepwear-pajamas",
  "https://www.dresslikemommy.com/en-gr/products/matching-maxi-double-rose-patchwork",
  "https://www.dresslikemommy.com/en-ch/products/matching-mermaid-scale-print-bikini",
  "https://www.dresslikemommy.com/en-fr/products/family-matching-christmas-deer-snowflake-pjs",
  "https://www.dresslikemommy.com/en-ie/products/dinosaur-family-matching-sweatshirts",
  "https://www.dresslikemommy.com/en-fr/products/mommy-me-matching-leopard-print-two-piece-swimsuit",
  "https://www.dresslikemommy.com/products/matching-summer-princess-skirt-dress",
  "https://www.dresslikemommy.com/en-ae/collections/family-matching/products/boho-chic-family-matching-outfit-flowy-skirts-and-paisley-shirts",
  "https://www.dresslikemommy.com/en-ch/collections/matching-couples-t-shirts/products/matching-tshirt-i-have-everything-i-need-i-am-everything",
  "https://www.dresslikemommy.com/en-gr",
  "https://www.dresslikemommy.com/en-se/products/matching-two-pieces-bikini-ruffle-swimsuit",
  "https://www.dresslikemommy.com/en-be/products/family-matching-blue-coconut-swimsuits",
  "https://www.dresslikemommy.com/en-ch/collections/matching-couples-t-shirts/products/couple-matching-queen-king-hearts-t-shirts",
  "https://www.dresslikemommy.com/en-jp/products/boho-chic-family-matching-outfit-flowy-skirts-and-paisley-shirts",
  "https://www.dresslikemommy.com/collections/family-matching/products/family-matching-floral-dress-set-mother-daughter-matching-outfits",
  "https://www.dresslikemommy.com/products/mommy-and-me-comfy-cotton-pajamas",
  "https://www.dresslikemommy.com/en-hk/collections/swimsuits/products/mother-daughter-matching-swim-set-abstract-print-two-piece-high-waisted-bikini-with-wrap-skirt",
  "https://www.dresslikemommy.com/collections/fall-winter/products/mother-and-daughter-floral-long-dress",
  "https://www.dresslikemommy.com/en-se/products/family-matching-battery-t-shirts",
  "https://www.dresslikemommy.com/products/family-matching-halloween-pajamas?variant=29830028099681",
  "https://www.dresslikemommy.com/collections/new-arrivals/products/mother-daughter-floral-print-jumpsuit-romper",
  "https://www.dresslikemommy.com/en-ch/products/mommy-me-matching-solid-long-dress",
  "https://www.dresslikemommy.com/en-ie/products/mommy-me-matching-solid-long-dress",
  "https://www.dresslikemommy.com/en-be/products/matching-long-sleeved-shirt",
  "https://www.dresslikemommy.com/collections/midi-dresses/products/mommy-me-matching-denim-dress",
  "https://www.dresslikemommy.com/en-ae/collections/swimsuits/products/chic-mother-daughter-matching-swimsuit-set-with-floral-cover-up-family-beachwear-collection",
  "https://www.dresslikemommy.com/collections/popular-mommy-me/products/mommy-me-matching-floral-v-sling-jumpsuit",
  "https://www.dresslikemommy.com/en-gr/products/mommy-me-matching-floral-one-piece-swimsuit",
  "https://www.dresslikemommy.com/en-hk/products/mommy-me-matching-floral-one-piece-swimsuit",
  "https://www.dresslikemommy.com/en-de/products/maternity-dresses-sweet-heart-chiffon-cloak-maxi-gown",
  "https://www.dresslikemommy.com/collections/popular-mommy-me-1/products/matching-sleeveless-color-stripes-jumpsuit",
  "https://www.dresslikemommy.com/en-be/products/family-matching-best-in-the-galaxy-t-shirts",
  "https://www.dresslikemommy.com/en-au/products/matching-family-christmas-tree-pajamas-xmas?variant=31287087071329",
  "https://www.dresslikemommy.com/en-gr/products/chic-mother-daughter-matching-swimsuit-set-with-floral-cover-up-family-beachwear-collection",
  "https://www.dresslikemommy.com/products/mother-and-daughter-long-sleeved-dress",
  "https://www.dresslikemommy.com/en-be/collections/all?page=20",
  "https://www.dresslikemommy.com/en-fr/products/chic-mother-daughter-matching-swimsuit-set-with-floral-cover-up-family-beachwear-collection",
  "https://www.dresslikemommy.com/a/s/products/mommy-me-spring-flowers-dress",
  "https://www.dresslikemommy.com/en-hk/products/mommy-me-matching-leopard-print-two-piece-swimsuit",
  "https://www.dresslikemommy.com/*/cart*",
  "https://www.dresslikemommy.com/products/floral-v-straps-jumpsuit-mommy-me",
  "https://www.dresslikemommy.com/collections/matching-outfits/products/matching-contrast-stitching-long-sleeve-t-shirt",
  "https://www.dresslikemommy.com/en-fr/collections/matching-outfits/products/family-matching-shirt-and-dress-set-yellow-floral-for-a-springtime-look",
  "https://www.dresslikemommy.com/products/2016-new-fashion-female-toucas-beanie-hat-knit-winter-hat-for-women-skullies-beanies-for-women-brand-hat-de-inverno-gorros?variant=24393928773",
  "https://www.dresslikemommy.com/en-au/products/mother-breastfeeding-short-sleeved-dress",
  "https://www.dresslikemommy.com/en-au/collections/new-arrivals/products/boho-chic-family-matching-outfit-flowy-skirts-and-paisley-shirts",
  "https://www.dresslikemommy.com/products/matching-family-christmas-tree-pajamas-xmas?variant=31287087431777",
  "https://www.dresslikemommy.com/products/matching-striped-ruffled-mid-skirt-dress",
  "https://www.dresslikemommy.com/en-jp/products/family-matching-tropical-swimsuits",
  "https://www.dresslikemommy.com/en-gr/collections/popular-mommy-me-1/products/chic-pink-mermaid-scales-tankini-set-for-mother-and-daughter",
  "https://www.dresslikemommy.com/en-au/collections/matching-outfits/products/family-matching-bathing-suits-swimwear?variant=39772839247969",
  "https://www.dresslikemommy.com/en-au/collections/new-arrivals/products/tropical-vibes-matching-family-hawaiian-shirt-and-floral-dress",
  "https://www.dresslikemommy.com/en-at/collections/mommy-me/products/mommy-me-flag-lace-patchwork-dress?variant=8144419848289",
  "https://www.dresslikemommy.com/collections/best-sellers/products/mommy-me-matching-rainbow-stripe-dress?variant=32471817453665",
  "https://www.dresslikemommy.com/en-fr/pages/secure-payments",
  "https://www.dresslikemommy.com/en-fr/collections/popular-mommy-me-1/products/mommy-me-matching-floral-v-sling-jumpsuit",
  "https://www.dresslikemommy.com/en-jp/products/maternity-photography-props-maxi-dresses-see-through-eyelashes-lace",
  "https://www.dresslikemommy.com/en-se/products/family-matching-boss-t-shirts",
  "https://www.dresslikemommy.com/en-au/collections/new-arrivals/products/family-matching-outfits-summer-boho-chic-dress-and-shirt",
  "https://www.dresslikemommy.com/en-ch/products/mommy-me-spring-flowers-dress",
  "https://www.dresslikemommy.com/en-au/products/matching-t-shirt-heart-rate-mommy-me",
  "https://www.dresslikemommy.com/products/mom-daughter-blessed-short-sleeve-t-shirts?variant=8106523721825",
  "https://www.dresslikemommy.com/en-be/collections/casual-dresses/products/charming-red-and-white-tie-dye-maxi-dresses-for-mother-and-daughter-perfect-for-spring-and-summer",
  "https://www.dresslikemommy.com/en-se/products/mom-and-me-grey-shabby-flower-headband-set-wedding-cute-lace-head-wraps-baby-mommy-rhinestone-hairband-1-set",
  "https://www.dresslikemommy.com/en-ae/collections/new-arrivals/products/boho-chic-family-matching-outfit-flowy-skirts-and-paisley-shirts",
  "https://www.dresslikemommy.com/en-jp/products/family-matching-rainbow-striped-sweater",
  "https://www.dresslikemommy.com/products/matching-t-shirt-heart-puzzle-piece",
  "https://www.dresslikemommy.com/collections/matching-outfits/products/mother-daughter-palace-princess-pajamas",
  "https://www.dresslikemommy.com/en-gr/collections/matching-outfits/products/parent-child-rainbow-bear-autumn-sweater",
  "https://www.dresslikemommy.com/en-ch/products/family-matching-tropical-swimsuits?variant=19604749418593",
  "https://www.dresslikemommy.com/products/matching-mother-daughter-long-sleeve-plaid-lace-patchwork-dress?variant=31302926139489",
  "https://www.dresslikemommy.com/en-gr/products/mother-daughter-matching-deer-print-party-dress",
  "https://www.dresslikemommy.com/en-hk/collections/daddy-me/products/daddy-and-me-the-best-kid-dad-t-shirt",
  "https://www.dresslikemommy.com/collections/family-matching-pajamas/products/family-matching-christmas-pajamas-set",
  "https://www.dresslikemommy.com/en-ie/collections/family-matching-pajamas/products/family-matching-christmas-pajamas-set",
  "https://www.dresslikemommy.com/products/mom-me-sleeveless-floral-maxi-dress",
  "https://www.dresslikemommy.com/en-fr/collections/swimsuits/products/chic-family-bonding-mother-daughter-matching-swimsuit-set-with-long-sleeved-cover-up",
  "https://www.dresslikemommy.com/en-ch/products/dinosaur-family-matching-sweatshirts",
  "https://www.dresslikemommy.com/en-at/products/enchanting-mermaid-scales-two-piece-swimsuit-set-for-mother-and-daughter-rainbow-hues-with-flirty-skirt-detail",
  "https://www.dresslikemommy.com/en-ae/products/mommy-me-angels-wing-swimsuit",
  "https://www.dresslikemommy.com/en-hk/collections/best-sellers/products/matching-maxi-double-rose-patchwork",
  "https://www.dresslikemommy.com/products/mother-and-daughter-short-sleeved-ruffled-dress",
  "https://www.dresslikemommy.com/collections/new-matching-outfits/products/matching-mom-and-daughter-pink-sequins-long-dress",
  "https://www.dresslikemommy.com/en-hk/collections/best-sellers/products/matching-maxi-purple-double-rose-patchwork",
  "https://www.dresslikemommy.com/products/matching-swimwear-mother-daughter?variant=7621368774686",
  "https://www.dresslikemommy.com/en-au/collections/fall-winter/products/matching-maxi-double-rose-patchwork",
  "https://www.dresslikemommy.com/en-ie/products/mommy-and-me-unicorn-sweater-fall-and-winter",
  "https://www.dresslikemommy.com/en-hk/collections/best-sellers/products/mother-and-daughter-floral-long-dress",
  "https://www.dresslikemommy.com/collections/casual-dresses/products/matching-black-short-sleeve-flower-dress",
  "https://www.dresslikemommy.com/en-se/products/mommy-and-me-unicorn-sweater-fall-and-winter",
  "https://www.dresslikemommy.com/en-hk/collections/best-sellers/products/mom-girl-flower-prints-stripes",
  "https://www.dresslikemommy.com/products/hot-sale-2016-new-fashion-winter-scarf-for-women-scarf-soft-warm-scarves-and-shawls-female-scarf-wholesale-retail",
  "https://www.dresslikemommy.com/en-fr/products/father-and-son-matching-swim-trunks-bold-cow-print-family-beachwear",
  "https://www.dresslikemommy.com/en-hk/collections/best-sellers/products/mommy-me-matching-floral-v-sling-jumpsuit",
  "https://www.dresslikemommy.com/en-au/products/matching-maxi-double-rose-patchwork",
  "https://www.dresslikemommy.com/products/matching-mother-daughter-long-sleeve-plaid-lace-patchwork-dress?variant=31302925779041",
  "https://www.dresslikemommy.com/en-jp/collections/family-matching/products/tropical-vibes-matching-family-hawaiian-shirt-and-floral-dress",
  "https://www.dresslikemommy.com/en-de/collections/new-arrivals/products/daddy-and-me-cartoon-t-shirt",
  "https://www.dresslikemommy.com/en-jp/products/mommy-me-leaf-print-open-waist-swimsuit",
  "https://www.dresslikemommy.com/products/halloween-family-matching-skeleton-pajamas-jumpsuit",
  "https://www.dresslikemommy.com/en-at/collections/pajamas",
  "https://www.dresslikemommy.com/en-gr/products/matching-red-cocktail-dress",
  "https://www.dresslikemommy.com/en-ee/products/long-beach-dress-mommy-me",
  "https://www.dresslikemommy.com/collections/new-matching-outfits/products/matching-sunflower-mother-daughter-one-piece-jumpsuits",
  "https://www.dresslikemommy.com/products/family-matching-clothes-hoodies-long-sleeve",
  "https://www.dresslikemommy.com/en-hk/collections/best-sellers/products/matching-leopard-thick-knit-long-sleeved-shirt",
  "https://www.dresslikemommy.com/en-gr/collections/new-matching-outfits/products/chic-two-piece-swimsuit-with-skirt-family-matching-swimwear-for-mother-and-daughter-available-in-blue-green-black",
  "https://www.dresslikemommy.com/en-ae/products/parent-child-rainbow-bear-autumn-sweater",
  "https://www.dresslikemommy.com/en-be/products/matching-mommy-me-unicorn-t-shirt",
  "https://www.dresslikemommy.com/en-be/products/tropical-vibes-matching-family-hawaiian-shirt-and-floral-dress",
  "https://www.dresslikemommy.com/en-at/collections/tops/products/matching-t-shirt-grl-pwr",
  "https://www.dresslikemommy.com/en-gr/collections/new-matching-outfits/products/mommy-me-vibrant-duo-tone-one-piece-swimsuit-with-ring-accent-family-matching-swimwear-collection",
  "https://www.dresslikemommy.com/en-ae/products/vibrant-halter-neck-one-piece-swimsuit-with-waist-tie-detail-mother-daughter-matching-swimwear-in-exquisite-baroque-print",
  "https://www.dresslikemommy.com/en-at/products/family-matching-boss-t-shirts",
  "https://www.dresslikemommy.com/en-gr/collections/new-matching-outfits/products/chic-family-bonding-mother-daughter-matching-swimsuit-set-with-long-sleeved-cover-up",
  "https://www.dresslikemommy.com/en-gr/products/father-and-son-matching-swim-trunks-classic-paisley-pattern-in-blue-and-yellow",
  "https://www.dresslikemommy.com/en-ae/products/daddy-and-me-big-man-little-man-t-shirt",
  "https://www.dresslikemommy.com/en-gr/collections/family-matching/products/memorable-family-matching-outfits-create-lasting-memories",
  "https://www.dresslikemommy.com/en-de/products/chic-family-tides-mother-daughter-matching-two-piece-swimsuit-with-skirt-vibrant-versatile-swimwear-collection",
  "https://www.dresslikemommy.com/en-se/collections/popular-mommy-me-1/products/mommy-me-matching-floral-v-sling-jumpsuit",
  "https://www.dresslikemommy.com/en-hk/collections/midi-dresses",
  "https://www.dresslikemommy.com/collections/casual-dresses/products/matching-mommy-me-sling-waist-jumpsuit-romper",
  "https://www.dresslikemommy.com/products/new-2020-matching-ruffled-one-shoulder-split-swimsuit",
  "https://www.dresslikemommy.com/products/mother-daughter-sleeveless-printed-matching-dress?variant=18470058328161",
  "https://www.dresslikemommy.com/en-hk/collections/swimsuits/products/mother-daughter-vibrant-two-piece-swimsuit-set-with-flowing-skirt-matching-family-swimwear-collection",
  "https://www.dresslikemommy.com/en-se/products/family-matching-king-queen-prince-princess-t-shirts",
  "https://www.dresslikemommy.com/en-gr/products/parent-child-rainbow-bear-autumn-sweater",
  "https://www.dresslikemommy.com/en-se/collections/popular-mommy-me-1/products/mother-and-daughter-floral-long-dress",
  "https://www.dresslikemommy.com/en-be/collections/midi-dresses",
  "https://www.dresslikemommy.com/collections/best-sellers/products/matching-maxi-purple-double-rose-patchwork",
  "https://www.dresslikemommy.com/en-gr/products/family-matching-best-in-the-galaxy-t-shirts",
  "https://www.dresslikemommy.com/products/2016-new-fashion-mom-and-me-headband-turban-headband-pair-set-top-knotted-headband-set-baby-and-mommy-cotton-headwrap-set-1-set-4",
  "https://www.dresslikemommy.com/en-fr/collections/daddy-me/products/father-and-son-matching-swim-trunks-tropical-paradise-red-and-green-print",
  "https://www.dresslikemommy.com/en-jp/pages/secure-payments",
  "https://www.dresslikemommy.com/en-be/collections/family-matching/products/make-a-splash-with-this-family-matching-floral-outfit",
  "https://www.dresslikemommy.com/collections/popular-mommy-me-1/products/mother-and-daughter-floral-long-dress",
  "https://www.dresslikemommy.com/wpm@0.0.262@3ea6f694we7e42bc0p486cfb65m48d4edfc/web-pixel-shopify-custom-pixel@0520/sandbox/products/casual-family-matching-outfits-mother-and-daughter-tees-father-and-son-t-shirts-mommy-and-baby-clothes-family-clothing?variant=21662271365",
  "https://www.dresslikemommy.com/en-be/products/family-matching-colorful-sweater-dad-mother-son-daughter",
  "https://www.dresslikemommy.com/en-at/collections/best-sellers/products/mom-girl-flower-prints-stripes",
  "https://www.dresslikemommy.com/products/matching-t-shirt-your-are-my-sunshine",
  "https://www.dresslikemommy.com/en-gr/collections/casual-dresses",
  "https://www.dresslikemommy.com/collections/midi-dresses/products/girl-mom-dress-family-clothing-2016-long-sleeve-print-floral-lace-dresses-for-me-and-mommy-mother-and-daugther-clothes-3xl",
  "https://www.dresslikemommy.com/en-ie/products/tropical-vibes-matching-family-hawaiian-shirt-and-floral-dress",
  "https://www.dresslikemommy.com/en-gr/collections/popular-mommy-me-1/products/mother-and-daughter-floral-long-dress",
  "https://www.dresslikemommy.com/en-be/products/stylish-and-comfortable-family-matching-outfits",
  "https://www.dresslikemommy.com/en-jp/products/family-matching-giraffe-sweater",
  "https://www.dresslikemommy.com/collections/midi-dresses/products/mother-daughter-matching-flower-dress",
  "https://www.dresslikemommy.com/en-au/collections/popular-family-matching/products/family-matching-need-more",
  "https://www.dresslikemommy.com/en-au/products/family-matching-summer-island-set",
  "https://www.dresslikemommy.com/products/family-matching-christmas-pajamas-festive-red-truck-christmas-tree-pajama-set-for-kids-adults-pets?variant=41886085447777&country=US&currency=USD",
  "https://www.dresslikemommy.com/collections/matching-outfits/products/family-matching-long-sleeve-swimwear",
  "https://www.dresslikemommy.com/en-jp/collections/maxi-dresses/products/matching-red-dress-mom-daughter",
  "https://www.dresslikemommy.com/en-au/products/mother-daughter-matching-deer-print-party-dress",
  "https://www.dresslikemommy.com/en-ch/collections/daddy-me/products/father-and-son-matching-swim-trunks-tropical-floral-print-family-swimwear",
  "https://www.dresslikemommy.com/wpm@0.0.262@3ea6f694we7e42bc0p486cfb65m48d4edfc/sandbox/products/mommy-me-matching-floral-one-piece-swimsuit?variant=39768880742497",
  "https://www.dresslikemommy.com/en-au/collections/mommy-me/products/chic-mother-daughter-two-piece-swimsuit-family-matching-swimwear-in-vibrant-colors",
  "https://www.dresslikemommy.com/en-ie/products/make-a-splash-with-this-family-matching-floral-outfit",
  "https://www.dresslikemommy.com/en-au/collections/maxi-dresses/products/matching-red-cocktail-dress",
  "https://www.dresslikemommy.com/products/matching-t-shirt-colorful-heart-mommy-me",
  "https://www.dresslikemommy.com/products/dads-cutest-catch-reel-cool-dad-t-shirt",
  "https://www.dresslikemommy.com/en-hk/products/matching-mommy-and-me-hollow-out-bikini",
  "https://www.dresslikemommy.com/en-ae/products/family-matching-rainbow-striped-sweater",
  "https://www.dresslikemommy.com/products/family-matching-christmas-pajamas-festive-red-truck-christmas-tree-pajama-set-for-kids-adults-pets?variant=41886085546081&country=US&currency=USD",
  "https://www.dresslikemommy.com/en-au/products/family-matching-battery-t-shirts"
];

const domain = "https://www.dresslikemommy.com";

// Collection mapping for known discontinued collections
const collectionMapping = {
  'maternity-dresses': '/collections/all',
  'maternity': '/collections/all',
  'swimwear': '/collections/family-matching-swimsuits',
  'swimsuits': '/collections/family-matching-swimsuits',
  'new-women-outfits': '/collections/all',
  'matching-outfits': '/collections/all',
  'new-matching-outfits': '/collections/all',
  'fall-winter': '/collections/all',
  'mini-dresses': '/collections/all',
  'maxi-dresses': '/collections/all',
  'midi-dresses': '/collections/all',
  'casual-dresses': '/collections/all',
  'formal-dresses': '/collections/all',
  'headbands': '/collections/all',
  'sundresses': '/collections/all',
  'skirts': '/collections/all',
  'jumpers': '/collections/all',
  'leggings': '/collections/all',
  'rompers': '/collections/all',
  'bottoms': '/collections/all',
  'tops': '/collections/all',
  'pants': '/collections/all',
  'matching-couples-t-shirts': '/collections/family-matching-t-shirts',
};

function getRedirectTarget(fullUrl) {
  let path;
  try {
    const u = new URL(fullUrl);
    path = u.pathname;
    // Strip query params and variants for the redirect path (Shopify redirects don't support query params)
  } catch(e) {
    return null;
  }

  // Skip invalid/junk URLs
  if (path.includes('wpm@') || path.includes('sandbox/') || path.includes('*/cart') || path === '/b' || path === '/comments' || path === '/thank_you' || path.includes('paginfo@') || path.includes('/a/s/')) {
    return '/collections/all';
  }

  // Strip locale prefix: /en-XX/...
  const localeMatch = path.match(/^\/en-[a-z]{2}(\/.*)?$/);
  let strippedPath = path;
  if (localeMatch) {
    strippedPath = localeMatch[1] || '/';
  }

  // Pattern: /collections/COLLECTION/products/PRODUCT → /products/PRODUCT
  const collProdMatch = strippedPath.match(/^\/collections\/[^\/]+\/products\/([^?]+)/);
  if (collProdMatch) {
    return '/products/' + collProdMatch[1];
  }

  // Pattern: /products/PRODUCT (with or without variant)
  const prodMatch = strippedPath.match(/^\/products\/([^?]+)/);
  if (prodMatch) {
    return '/products/' + prodMatch[1];
  }

  // Pattern: /collections/COLLECTION
  const collMatch = strippedPath.match(/^\/collections\/([^?]+)/);
  if (collMatch) {
    const collSlug = collMatch[1].replace(/\?.*$/, '').replace(/\/+$/, '');
    if (collectionMapping[collSlug]) {
      return collectionMapping[collSlug];
    }
    return '/collections/' + collSlug;
  }

  // Pattern: /pages/PAGE
  const pageMatch = strippedPath.match(/^\/pages\/([^?]+)/);
  if (pageMatch) {
    return '/pages/' + pageMatch[1];
  }

  // Pattern: /account/register
  if (strippedPath.includes('/account/register')) {
    return '/account/register';
  }

  // Root locale pages
  if (strippedPath === '/' || strippedPath === '') {
    return '/';
  }

  // Anything else → /collections/all
  return '/collections/all';
}

// Process all URLs
const redirects = new Map(); // Use Map to deduplicate by "from" path
let skipped = 0;

for (const fullUrl of rawUrls) {
  let fromPath;
  try {
    const u = new URL(fullUrl);
    fromPath = u.pathname;
    // Shopify redirects only work with path (no query string)
    // But we need to include the path as-is
  } catch(e) {
    skipped++;
    continue;
  }

  const target = getRedirectTarget(fullUrl);
  if (!target) {
    skipped++;
    continue;
  }

  // Don't redirect to self
  if (fromPath === target) {
    skipped++;
    continue;
  }

  // Don't include if already have this redirect from path
  if (!redirects.has(fromPath)) {
    redirects.set(fromPath, target);
  }
}

// Generate CSV
let csv = 'Redirect from,Redirect to\n';
let count = 0;
for (const [from, to] of redirects) {
  csv += `"${from}","${to}"\n`;
  count++;
}

fs.writeFileSync('dlm-bulk-redirects.csv', csv, 'utf8');

// Stats
const stats = {
  total_urls: rawUrls.length,
  unique_redirects: count,
  skipped: skipped,
  patterns: {}
};

for (const [from, to] of redirects) {
  if (from.match(/^\/en-[a-z]{2}\//)) {
    stats.patterns['locale_prefix'] = (stats.patterns['locale_prefix'] || 0) + 1;
  } else if (from.match(/^\/collections\/[^\/]+\/products\//)) {
    stats.patterns['collection_product'] = (stats.patterns['collection_product'] || 0) + 1;
  } else if (from.match(/^\/products\//)) {
    stats.patterns['dead_product'] = (stats.patterns['dead_product'] || 0) + 1;
  } else if (from.match(/^\/collections\//)) {
    stats.patterns['dead_collection'] = (stats.patterns['dead_collection'] || 0) + 1;
  } else {
    stats.patterns['other'] = (stats.patterns['other'] || 0) + 1;
  }
}

console.log(JSON.stringify(stats, null, 2));
console.log(`\nCSV saved to dlm-bulk-redirects.csv with ${count} redirects`);
